#!/bin/bash


if [[ $1 == "-h" ]]; then

    echo -e "\nUsage: pull_SeqRec [USER_ORGANISM] [USER_ORGANISM_ACCESSION_FILE]"
    echo -e "\nMake sure organism name is the same as the one used in get_WGSreads.sh to obtain the accession file. Also make sure organism name is in quotes if using more than one word (as in a species name)."
    echo "Provide run accession after organism name. A new directory will be created based on the name of this file to contain downloaded sequences."
    echo "If a file is not provided, the script will error out."
    echo "Run get_SeqRec -F USER_ORGANISM RNA-seq to get SRR list to input into pull_SeqRec. This script requires SRA Toolkit, please load local/cluster module."
    echo -e "\nExamples: pull_SeqRec \"Macaca mulatta\" Macacamulatta~run_accession_Apr_19.txt | pull_SeqRec mouse mouse~run_accession_April_20.txt" 
    echo -e "\nOption flag:"
    echo -e "  -h\t Print this help message"

elif [[ $# -lt 2 ]]; then

    echo "Please provide an organism followed by a list of SRR IDs. run get_SeqRec -F USR_ORGN RNA-seq for example input file. Try -h for help"
    exit 0

else

    org=$1
    genus=$(echo $org|awk '{print $1}')
    species=$(echo $org|awk '{print $2}')
    cdate=$(date|awk '{OFS="_"}{print $2,$3}')

##only useful at command line 
#    read -e -p "Enter run accession list filename (run 'get_SeqReads -F' for example output file): " runs
    echo " "
    echo "File used: $2"
    runs=$2

    asc="sra/2.8.1"
    pbs="sratoolkit/2.8.0"

    if [[ ! -s $runs ]]; then
        echo "File is empty. Please provide SRR list; try pull_SeqRec -h for more information"
        exit 0
    else

        ##Modules and Variables
        if [ "${HOSTNAME:0:9}" == "dmcvlogin" ]; then
                module load $asc
                echo "Loaded SRA Toolkit: $asc "
        fi

        if [ -n "$PBS_JOBNAME" ]; then
                module load $pbs
                echo "Loaded SRA Toolkit: $pbs "

        fi
        echo " "
        echo " "

        mkdir $genus$species~files_$cdate
        sd="./$genus$species~files_$cdate/"

        echo "Created the following directory for sequencing reads: $sd"
        echo " "
        echo "====================================================="

        add=0
        for run in $(cat $runs ); do
            let add++
            tot=$(cat $runs|wc -l)
            fastq-dump -v --split-files -I --gzip -O $sd $run


            echo "$add of $tot sequences downloaded to $sd"
            echo "----------------------------------------"
        done


        echo " "
        echo "====================================================="
        echo "Download Complete! Sequences can be found in $sd"

    fi
fi
